#define MAX_LAYER 32
#define LAYER_STATE_32BIT

#define AUTO_SHIFT_REPEAT
#define MOUSEKEY_MAX_SPEED 2
#define UNICODE_SELECTED_MODES UC_LNX
#define CAPS_WORD_TOGGLE_KEY

#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
/* #define RGBLIGHT_MODE_STATIC_LIGHT */
/* #define RGBLIGHT_MODE_RAINBOW_MOOD */
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
/* #define RGBLIGHT_MODE_STATIC_GRADIENT */
/* #define RGBLIGHT_MODE_RGB_TEST */
/* #define RGBLIGHT_MODE_ALTERNATING */
#define RGBLIGHT_EFFECT_TWINKLE

#define COMBO_COUNT 110

/* #define ENABLE_RGB_MATRIX_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_SAT_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_HUE_STAR_LIGHT */
