#pragma once
#define I2C_DRIVER I2CD1

  /* #define USE_WORKMAN 1 */
#define MOUSEKEY_MAX_SPEED 2
#define UNICODE_SELECTED_MODES UC_LNX
#define CAPS_WORD_TOGGLE_KEY

#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
/* #define RGBLIGHT_MODE_STATIC_LIGHT */
/* #define RGBLIGHT_MODE_RAINBOW_MOOD */
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_MODE_STATIC_GRADIENT
/* #define RGBLIGHT_MODE_RGB_TEST */
/* #define RGBLIGHT_MODE_ALTERNATING */
#define RGBLIGHT_EFFECT_TWINKLE


/* #define ENABLE_RGB_MATRIX_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_SAT_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_HUE_STAR_LIGHT */

#include "../../../common/config.h"

#define UNICODE_KEY_LNX	LCTL(LSFT(KC_U))

#define DYNAMIC_MACRO_DELAY 100


#define USB_SUSPEND_WAKEUP_DELAY 0
#define LAYER_STATE_32BIT

#define RGB_MATRIX_STARTUP_SPD 60

#undef DEBOUNCE
#define DEBOUNCE 2

#undef TAPPING_TERM
#define TAPPING_TERM 195

#undef IGNORE_MOD_TAP_INTERRUPT

/* #undef TAPPING_TOGGLE */
/* #define TAPPING_TOGGLE 1 */

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0


#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 20

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 30

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 50

#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 4

#define FORCE_NKRO


#undef AUTO_SHIFT_TIMEOUT
#define AUTO_SHIFT_TIMEOUT 150

#define NO_AUTO_SHIFT_TAB
/* #define CAPS_LOCK_STATUS */
#define HOLD_ON_OTHER_KEY_PRESS

/* #define COMBO_STRICT_TIMER */
#undef COMBO_TERM
#define COMBO_TERM 37  // default is 50.  50ms produces false positives when typing kinda fast
#undef COMBO_COUNT
#define COMBO_COUNT 300

#define AUTO_SHIFT_REPEAT

#define FLOW_TAP_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD

/* #define COMBO_ONLY_FROM_LAYER 0 */
