#define AUTO_SHIFT_REPEAT
#define MOUSEKEY_MAX_SPEED 2
#define UNICODE_SELECTED_MODES UC_LNX
#define CAPS_WORD_TOGGLE_KEY


/* #define ENABLE_RGB_MATRIX_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_SAT_STAR_LIGHT */
/* #define ENABLE_RGB_MATRIX_DUAL_HUE_STAR_LIGHT */
