enum custom_keycodes {
                      RGB_SLD = ML_SAFE_RANGE,
                      EMACS_OTHER_WINDOW,
                      EMACS_BUFFER_REVERT,
                      FISH_ACCEPT_SEND,
                      EMACS_YAS_DOC,
                      EMACS_YAS_TF,
                      EMACS_YAS_C,
                      EMACS_YAS_TL,
                      EMACS_YAS_MAP_ANON,
                      EMACS_ACE_WINDOW_SWAP,
                      EMACS_WINDOW_CLOSE,
                      EMACS_WINDOW_CLOSEST_MACRO_12,
                      EMACS_INSERT_GET_FEED,
                      MUSIC_LAYER_ACTIVATE,
                      SHIFTLOK_LAYER_ACTIVATE,
                      SHIFTLOK_LAYER_DEACTIVATE,
                      SYSTEM_LAYER_ACTIVATE,
                      SYSTEM_LAYER_DEACTIVATE,
};
