enum layers {_BASE,
             _LOWER,
             _RAISE,
             _MOUSE,
             _SYSTEM,
             _WINDOWS,
             _MACROS,
             _SHIFTLOK,
             _WINMOVE,
             _META,
             _SUPER,
             _EDITING,
             _SYMBOLS,
};
