/* enum tap_dance_codes { */
/*                       DANCE_0, */
/*                       DANCE_1, */
/*                       DANCE_2, */
/*                       DANCE_3, */
/*                       DANCE_4, */
/*                       DANCE_5, */
/*                       DANCE_6, */
/*                       DANCE_7, */
/*                       DANCE_8, */
/*                       DANCE_9, */
/*                       DANCE_10, */
/*                       DANCE_11, */
/*                       DANCE_12, */
/*                       DANCE_13, */
/*                       DANCE_14, */
/*                       DANCE_15, */
/*                       DANCE_16, */
/*                       DANCE_17, */
/*                       DANCE_18, */
/*                       DANCE_19, */
/*                       DANCE_20, */
/*                       DANCE_21, */
/*                       DANCE_22, */
/*                       DANCE_23, */
/*                       DANCE_24, */
/*                       DANCE_25, */
/*                       DANCE_26, */
/*                       DANCE_27, */
/*                       DANCE_28, */
/*                       DANCE_29, */
/*                       DANCE_30, */
/*                       DANCE_31, */
/*                       DANCE_32, */
/*                       DANCE_33, */
/*                       DANCE_34, */
/*                       DANCE_35, */
/*                       DANCE_36, */
/*                       DANCE_37, */
/*                       DANCE_38, */
/*                       DANCE_39, */
/*                       DANCE_40, */
/*                       DANCE_41, */
/*                       DANCE_42, */
/*                       DANCE_43, */
/*                       DANCE_44, */
/*                       DANCE_45, */
/*                       DANCE_46, */
/*                       DANCE_47, */
/*                       DANCE_48, */
/* }; */
