#pragma once

#define AUTO_SHIFT_REPEAT
#define MOUSEKEY_MAX_SPEED 2
#define UNICODE_SELECTED_MODES UC_LNX
#define CAPS_WORD_TOGGLE_KEY
#define RGB_MATRIX_LED_COUNT 24


/* #define WS2812 */

/* #define I2C_DRIVER I2CD1 */
/* #define RGB_MATRIX_LED_COUNT 24 */
/* #define DRIVER_LED_TOTAL 24 */
/* #define DRIVER_COUNT 1 */

/* #define RGBLIGHT_ENABLE */
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
/* #define RGBLIGHT_MODE_STATIC_LIGHT */
/* #define RGBLIGHT_MODE_RAINBOW_MOOD */
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_MODE_STATIC_GRADIENT
/* #define RGBLIGHT_MODE_RGB_TEST */
/* #define RGBLIGHT_MODE_ALTERNATING */
#define RGBLIGHT_EFFECT_TWINKLE


#include "../../../common/config.h"
