# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = IS31FL3731

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLED_SPLIT = yes


# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = WS2812

AUTO_SHIFT_ENABLE = yes
AUTO_SHIFT_MODIFIERS = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes
MIDI_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ANIMATIONS = yes
RGBLIGHT_ENABLE = yes
RGB_ANIMATIONS = yes
TAP_DANCE_ENABLE = yes
WEBUSB_ENABLE = yes

# UNICODE_ENABLE = yes
# UNICODEMAP_ENABLE = yes
# UCIS_ENABLE = yes
