SRC += muse.c

# UCIS_ENABLE = yes
# UNICODEMAP_ENABLE = yes
# UNICODE_ENABLE = yes
AUDIO_ENABLE = yes
AUTOCORRECT_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
AUTO_SHIFT_MODIFIERS = yes
# BACKLIGHT_ENABLE = yes       # Enable keyboard backlight functionality
BOOTLOADER = atmel-dfu
# BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
# COMMAND_ENABLE = no         # Commands for debug and configuration
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes       # Audio control and System control
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes
LTO_ENABLE = yes
MCU = atmega32u4
MIDI_ENABLE = yes
MOUSEKEY_ENABLE = no        # Mouse keys
NKRO_ENABLE = yes
RGBLIGHT_ANIMATIONS = yes
RGBLIGHT_ENABLE = yes
RGB_ANIMATIONS = yes
RGB_MATRIX_DRIVER = WS2812
RGB_MATRIX_ENABLE = yes
SPLIT_KEYBOARD = yes
TAP_DANCE_ENABLE = yes
WEBUSB_ENABLE = yes
